Misc/reduce memory usage
MeteoSwiss/mlpp-features pull request #29
Opened 2024-07-17 15:26 UTC by louisPoulain

Add chunking to reduce memory consumption when using a large number of stations.

2024-07-17 15:34 UTC, dnerini approved these changes

2024-07-17 15:36 UTC, dnerini reviewed
Uhm I'm a bit hesitant to hardcode the chunk sizes here, since this is very much dependent on use cases. What do you think?

2024-07-17 16:04 UTC, louisPoulain commented
> Uhm I'm a bit hesitant to hardcode the chunk sizes here, since this is very much dependent on use cases. What do you think?

I agree, but I'm unsure where to specify it. Or do we pass it as a kwargs to the preproc.interp ? That way we don't have a breaking change as everything would be controlled in the workflow itself.

2024-07-19 07:24 UTC, dnerini requested changes
do not use hardcoded chunks

2024-09-11 12:51 UTC, closed without merging